package(default_visibility = ["//visibility:public"])

licenses(["notice"])  # Apache 2.0

py_library(
    name = "estimator_util",
    srcs = ["estimator_util.py"],
    srcs_version = "PY2AND3",
    deps = [
        "//astronet/ops:dataset_ops",
        "//astronet/ops:metrics",
        "//astronet/ops:training",
    ],
)

py_library(
    name = "config_util",
    srcs = ["config_util.py"],
    srcs_version = "PY2AND3",
)

py_library(
    name = "configdict",
    srcs = ["configdict.py"],
    srcs_version = "PY2AND3",
)

